---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- {name: boshrelease-ci}
- {name: dockerfile-repo}
- {name: patroni}

outputs:
- {name: dockerfile}

params:
  dockerfile_root:

run:
  path: ./boshrelease-ci/ci/tasks/prepare-dockerfile.sh
