backups_clusterdata_aws_access_key_id: (( vault $VAULT_PREFIX "/aws/clusterdata:aws_access_key_id" ))
backups_clusterdata_aws_secret_access_key: (( vault $VAULT_PREFIX "/aws/clusterdata:aws_secret_access_key" ))
backups_database_storage_aws_access_key_id: (( vault $VAULT_PREFIX "/aws/database_storage:aws_access_key_id" ))
backups_database_storage_aws_secret_access_key: (( vault $VAULT_PREFIX "/aws/database_storage:aws_secret_access_key" ))
